//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Role()
        {
            this.Sys_Role_Permission = new HashSet<Sys_Role_Permission>();
            this.Sys_User_Role = new HashSet<Sys_User_Role>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> FatherRoleID { get; set; }
        public int IsSysRole { get; set; }
        public int IsEnable { get; set; }
        public int RoleType { get; set; }
        public Nullable<int> ShowOrder { get; set; }
        public string Remark { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Role_Permission> Sys_Role_Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_User_Role> Sys_User_Role { get; set; }
    }
}
