//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log
    {
        public int LogID { get; set; }
        public string UserIP { get; set; }
        public int LogType { get; set; }
        public string LogContent { get; set; }
        public System.DateTime AddOn { get; set; }
        public string AddBy { get; set; }
        public string AddByName { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
