//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_User()
        {
            this.Sys_User_Permission = new HashSet<Sys_User_Permission>();
            this.Sys_User_Role = new HashSet<Sys_User_Role>();
        }
    
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int Sex { get; set; }
        public int UserType { get; set; }
        public string Department { get; set; }
        public string Duties { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public int IsEnable { get; set; }
        public Nullable<System.DateTime> LastLoginData { get; set; }
        public int LoginTimes { get; set; }
        public System.DateTime AddOn { get; set; }
        public string AddBy { get; set; }
        public byte[] RowVersion { get; set; }
        public int GlobalPageSize { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_User_Permission> Sys_User_Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_User_Role> Sys_User_Role { get; set; }
    }
}
